### ISSUE TITLE
crash in stopEdit

### ISSUE THREAD

**Issue by denis-adamchuk** [denis-adamchuk/mrHelper#254]
4/16/2020 14:34:16 UTC: mrHelper.exe Error: 0 : Unhandled exception: [System.NullReferenceException] Object reference not set to an instance of an object.
Callstack:
   at mrHelper.App.Controls.DiscussionBox.stopEdit(TextBox textBox)
   at mrHelper.App.Controls.DiscussionBox.<onSubmitNewBodyAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task ask)
   at mrHelper.App.Controls.DiscussionBox.<TextBox_LostFocus>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by denis-adamchuk** [comment]
Steps:
While editing, r-click on file name and press Resolve Thread
