### ISSUE TITLE
Crash on Alt-K

### ISSUE THREAD

**Issue by denis-adamchuk** [denis-adamchuk/mrHelper#586]
```
2/20/2023 17:04:47 UTC: mrHelper.exe Error: 0 : [mrHelper.Core.Context.ContextMakingException] Failed to obtain DiffContext: Cannot determine a line state 
[mrHelper.StorageSupport.GitDiffAnalyzerException] Cannot obtain git diff 
[mrHelper.StorageSupport.GitNotAvailableDataException]  
[mrHelper.StorageSupport.GitCommandServiceInternalException]  
[mrHelper.StorageSupport.ArgumentConversionException] Bad filename pair 
2/20/2023 17:04:47 UTC: mrHelper.exe Error: 0 : Unhandled exception (nested): [System.ArgumentNullException] Value cannot be null.
Parameter name: source
Callstack:
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at mrHelper.Core.Context.DiffContext.GetLongestLine()
   at mrHelper.App.Forms.NewDiscussionForm.getContextHtmlText(DiffPosition position, HtmlPanel htmlPanel)
   at mrHelper.App.Forms.NewDiscussionForm.showDiscussionContext(DiffPosition position, HtmlPanel htmlPanel)
   at mrHelper.App.Forms.NewDiscussionForm.updateRelatedDiscussionControlState()
   at mrHelper.App.Forms.NewDiscussionForm.updateControlState()
   at mrHelper.App.Forms.NewDiscussionForm.NewDiscussionForm_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by denis-adamchuk** [comment]
GitDiffAnalyzerException thrown from GitDiffAnalyzer.getDiffSections() is not handled in this call-stack:
```
>	mrHelper.StorageSupport.GitDiffAnalyzer.getDiffSections Line 102	C#	Symbols loaded.
 	mrHelper.StorageSupport.GitDiffAnalyzer.IsLineAddedOrModified Line 53	C#	Symbols loaded.
 	mrHelper.Core.Context.EnhancedContextMaker.getLineState Line 122	C#	Symbols loaded.
 	mrHelper.Core.Context.EnhancedContextMaker.getLineContext Line 107	C#	Symbols loaded.
 	mrHelper.Core.Context.EnhancedContextMaker.createDiffContext Line 93	C#	Symbols loaded.
 	mrHelper.Core.Context.EnhancedContextMaker.GetContext Line 73	C#	Symbols loaded.
 	mrHelper.App.Interprocess.DiffCallHandler.getDiffContext<mrHelper.Core.Context.EnhancedContextMaker> Line 249	C#	Symbols loaded.
 	mrHelper.App.Interprocess.DiffCallHandler.showNewDiscussionDialog.__fnGetNewDiscussionDiffContext|6 Line 102	C#	Symbols loaded.
 	mrHelper.App.Forms.NewDiscussionForm.getContextHtmlText Line 604	C#	Symbols loaded.
 	mrHelper.App.Forms.NewDiscussionForm.showDiscussionContext Line 585	C#	Symbols loaded.
 	mrHelper.App.Forms.NewDiscussionForm.updateRelatedDiscussionControlState Line 740	C#	Symbols loaded.
 	mrHelper.App.Forms.NewDiscussionForm.updateControlState Line 643	C#	Symbols loaded.
 	mrHelper.App.Forms.NewDiscussionForm.NewDiscussionForm_Load Line 90	C#	Symbols loaded.
```

The exception originates from this code:
```
      private static void throwOnBadFilenamePair(string filename1, string filename2)
      {
         bool isFilename1Empty = String.IsNullOrEmpty(filename1);
         bool isFilename2Empty = String.IsNullOrEmpty(filename2);
         if (isFilename1Empty != isFilename2Empty)
         {
            throw new ArgumentConversionException("Bad filename pair", null);
         }
      }
```
What means that one of filenames in a _related discussion_ is null. That happens. It is handled in Discussions view.
